before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pYxjZ+aP0A2QmMCJ+eu019JDtGGYFh0e4SN5gvi9GUrAdap7WiOg7yj20Vqk2GUr0m+QOvc7OBhXXt5tVWRGLOud9IN4yF/2vl739f/b/pxL5dXfsBsApwxCgnX1LwOahSDUaJAE252ER8XY7CgWdaqpAQq7mUmTY4OCaFBMvUGPacUnOg1d9+Daml6caWpNa3hsAW5q+6C4WqNfCv8dDkWXA9D4c5bBiL3ZjDyQL7EY8c/nkZy31MFI0VRjizt5ZiWdRfanGFVEfM+NszzUxpyWBSKHPRjRK5IRnsWYTVBONL087OStsb2jB7aPnzEK65cUcQpULnVpiyE1+eXQbLXgXDyAjckdvoxoiWZUMH2XwsY7qQ4zwrNGeNNxC1OOcqDWAeKnhvkD089BzmhLxLXwTe/GDVrhLwLTiosCizSePpVqxRfjdiUbXWm7Xsjou0X/dE4zXkiQzbTBqAN9hzMLv+vOWEDpZHgBpU8/esT3mYSkD04twl6PCI8JRfFCm6r/DvL8AyFRhwf0wZRwndwq81d0qKeRt3svNIIDIxXhzl3DeT7Up/x0WHQ4F0YHNH89y3IqSB+bmscKLGyHr/Ipt8Xz1wEhkHMHezmVbgtNNCXWVB+wveFqN83R9AVDosaWWp/fckzP6fD3PDR9Ow+hXZmp1TjCU6+6pW79H3g= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
